# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            pionerias discretas
tagline:          'por Fabrizio R.'
description:      'Página reservada para assuntos escoteiros, tecnologia, projetos pessoais, sociais e pensamentos aleatórios'
url:              http://lanyon.getpoole.com

author:
  name:           'Fabrizio R.'
  url:            https://twitter.com/fabriziox

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
